# Generated by Django 3.1.2 on 2020-10-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20201010_0608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Category',
            new_name='category',
        ),
        migrations.AddField(
            model_name='image',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
